# Generated by Django 4.0.1 on 2022-01-20 18:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_idea_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='idea',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
