# Generated by Django 4.0.1 on 2022-01-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
